# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final2024_q2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(556, 491)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 481, 331))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_generatenumbers = QtWidgets.QPushButton(self.widget)
        self.pushButton_generatenumbers.setObjectName("pushButton_generatenumbers")
        self.gridLayout.addWidget(self.pushButton_generatenumbers, 0, 0, 1, 5)
        self.label_numbers = QtWidgets.QLabel(self.widget)
        self.label_numbers.setObjectName("label_numbers")
        self.gridLayout.addWidget(self.label_numbers, 1, 0, 1, 2)
        self.textEdit_number = QtWidgets.QTextEdit(self.widget)
        self.textEdit_number.setObjectName("textEdit_number")
        self.gridLayout.addWidget(self.textEdit_number, 2, 0, 1, 5)
        self.radioButton_max = QtWidgets.QRadioButton(self.widget)
        self.radioButton_max.setObjectName("radioButton_max")
        self.gridLayout.addWidget(self.radioButton_max, 3, 0, 1, 1)
        self.radioButton_min = QtWidgets.QRadioButton(self.widget)
        self.radioButton_min.setObjectName("radioButton_min")
        self.gridLayout.addWidget(self.radioButton_min, 3, 1, 1, 1)
        self.radioButton_sort = QtWidgets.QRadioButton(self.widget)
        self.radioButton_sort.setObjectName("radioButton_sort")
        self.gridLayout.addWidget(self.radioButton_sort, 3, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 3, 1, 1)
        self.radioButton_reverse = QtWidgets.QRadioButton(self.widget)
        self.radioButton_reverse.setObjectName("radioButton_reverse")
        self.gridLayout.addWidget(self.radioButton_reverse, 3, 4, 1, 1)
        self.label_result = QtWidgets.QLabel(self.widget)
        self.label_result.setObjectName("label_result")
        self.gridLayout.addWidget(self.label_result, 4, 0, 1, 2)
        self.textEdit_result = QtWidgets.QTextEdit(self.widget)
        self.textEdit_result.setObjectName("textEdit_result")
        self.gridLayout.addWidget(self.textEdit_result, 5, 0, 1, 5)
        self.label_status = QtWidgets.QLabel(self.widget)
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_generatenumbers.setText(_translate("Form", "Generate Numbers"))
        self.label_numbers.setText(_translate("Form", "Numbers"))
        self.radioButton_max.setText(_translate("Form", "Max"))
        self.radioButton_min.setText(_translate("Form", "Min"))
        self.radioButton_sort.setText(_translate("Form", "Sort"))
        self.comboBox.setItemText(0, _translate("Form", "Ascending"))
        self.comboBox.setItemText(1, _translate("Form", "Descending"))
        self.radioButton_reverse.setText(_translate("Form", "Reverse"))
        self.label_result.setText(_translate("Form", "Result"))
        self.label_status.setText(_translate("Form", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
