# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalw2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(328, 368)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_asal = QtWidgets.QTextEdit(Form)
        self.textEdit_asal.setObjectName("textEdit_asal")
        self.gridLayout.addWidget(self.textEdit_asal, 0, 0, 1, 3)
        self.label_enter_number = QtWidgets.QLabel(Form)
        self.label_enter_number.setObjectName("label_enter_number")
        self.gridLayout.addWidget(self.label_enter_number, 1, 0, 1, 1)
        self.lineEdit_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.gridLayout.addWidget(self.lineEdit_number, 1, 1, 1, 2)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 2)
        self.pushButton_run = QtWidgets.QPushButton(Form)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 2, 2, 1, 1)
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 3, 0, 1, 2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_enter_number.setText(_translate("Form", "Enter Number"))
        self.comboBox.setCurrentText(_translate("Form", "Print the text box"))
        self.comboBox.setItemText(0, _translate("Form", "Print the text box"))
        self.comboBox.setItemText(1, _translate("Form", "Write the file"))
        self.pushButton_run.setText(_translate("Form", "RUN"))
        self.label_status.setText(_translate("Form", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
